// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cms

import (
	"mocking_api/config/database"
)

// Injectors from wire.go:

func InitializeCms() routes {
	db := database.InitSqlite()
	cmsRepository := newRepository(db)
	cmsService := newService(cmsRepository)
	cmsController := newController(cmsService)
	cmsRoutes := newRoutes(cmsController)
	return cmsRoutes
}
