// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package health

// Injectors from wire.go:

func InitializeHealthCheck() (routes, error) {
	healthController := newController()
	healthRoutes := newRoutes(healthController)
	return healthRoutes, nil
}
