// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dukcapil

// Injectors from wire.go:

func InitializeDukcapil() (routes, error) {
	dukcapilController := newController()
	dukcapilRoutes := newRoutes(dukcapilController)
	return dukcapilRoutes, nil
}
